# Generated by Django 4.0.1 on 2022-03-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagehelp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymenthelp',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrdersHelp',
        ),
        migrations.DeleteModel(
            name='PackageHelp',
        ),
        migrations.DeleteModel(
            name='PaymentHelp',
        ),
    ]
