# Generated by Django 4.0.1 on 2022-03-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershelp',
            name='image',
            field=models.ImageField(null=True, upload_to='help/user/'),
        ),
        migrations.AddField(
            model_name='packagehelp',
            name='image',
            field=models.ImageField(null=True, upload_to='help/user/'),
        ),
        migrations.AddField(
            model_name='paymenthelp',
            name='image',
            field=models.ImageField(null=True, upload_to='help/user/'),
        ),
    ]
