# Generated by Django 4.0.1 on 2022-02-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumclothname',
            name='cloth_category_name',
        ),
        migrations.RemoveField(
            model_name='premiumclothservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='premiumorderssummary',
            name='cloth_name',
        ),
        migrations.RemoveField(
            model_name='premiumorderssummary',
            name='user',
        ),
        migrations.DeleteModel(
            name='PremiumClothCategory',
        ),
        migrations.DeleteModel(
            name='PremiumClothName',
        ),
        migrations.DeleteModel(
            name='PremiumClothService',
        ),
        migrations.DeleteModel(
            name='PremiumOrdersSummary',
        ),
    ]
