# Generated by Django 4.0.1 on 2022-02-24 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premium', '0002_remove_premiumclothname_cloth_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumClothCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/coth/category/')),
                ('cloth_category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumClothName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=250)),
                ('number_of_clothes', models.CharField(max_length=250)),
                ('cloth_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.premiumclothcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumOrdersSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_image', models.ImageField(null=True, upload_to='image/')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('ironing', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('cold_water', models.BooleanField(default=False)),
                ('washing_liquid', models.BooleanField(default=False)),
                ('softern', models.BooleanField(default=False)),
                ('puckup_date', models.DateField()),
                ('delivery', models.DateField(null=True)),
                ('instruction', models.CharField(max_length=150)),
                ('paid', models.BooleanField(default=False)),
                ('cloth_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.premiumclothname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumClothService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField()),
                ('premium_service_price', models.CharField(max_length=150)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
