# Generated by Django 4.0.1 on 2022-02-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_alter_premiumclothservice_premium_service_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumclothname',
            old_name='number_of_clothes',
            new_name='number_of_service',
        ),
        migrations.RemoveField(
            model_name='premiumclothservice',
            name='service',
        ),
        migrations.AddField(
            model_name='premiumclothname',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='premiumclothcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='media/premium/category/'),
        ),
    ]
