# Generated by Django 4.0.1 on 2022-02-25 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_rename_number_of_clothes_premiumclothname_number_of_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumClothService',
        ),
    ]
