# Generated by Django 3.1.7 on 2022-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0011_auto_20220225_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumclothservice',
            name='premium_services_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
