# Generated by Django 3.1.7 on 2022-02-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0012_auto_20220226_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumclothname',
            name='number_of_service',
        ),
        migrations.RemoveField(
            model_name='premiumclothname',
            name='price',
        ),
    ]
