# Generated by Django 3.1.7 on 2022-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0013_auto_20220227_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumServicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=150)),
            ],
        ),
    ]
