# Generated by Django 3.1.7 on 2022-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0014_premiumserviceprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumorderssummary',
            name='price',
        ),
    ]
