# Generated by Django 3.2.3 on 2022-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0016_auto_20220226_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumorderssummary',
            name='cloth_name',
            field=models.CharField(max_length=250),
        ),
    ]
