# Generated by Django 3.2.3 on 2022-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0017_alter_premiumorderssummary_cloth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumorderssummary',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
