# Generated by Django 3.1.7 on 2022-02-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_category_orderssummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderssummary',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderssummary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='OrdersSummary',
        ),
    ]
