# Generated by Django 3.1.7 on 2022-02-15 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20220215_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClothName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=250)),
                ('cloth_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.clothcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('ironing', models.BooleanField(default=False)),
                ('cloth_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.clothname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
