# Generated by Django 3.1.7 on 2022-02-15 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_auto_20220215_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=250)),
                ('price', models.FloatField(null=True)),
                ('number_of_clothes', models.CharField(max_length=250)),
                ('cloth_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.clothcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('ironing', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('cold_water', models.BooleanField(default=False)),
                ('washing_liquid', models.BooleanField(default=False)),
                ('softern', models.BooleanField(default=False)),
                ('puckup_date', models.DateField()),
                ('delivery_date', models.DateTimeField()),
                ('order_summary', models.CharField(max_length=150)),
                ('cloth_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.clothname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
