# Generated by Django 3.1.7 on 2022-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220215_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderssummary',
            name='clothimage',
            field=models.ImageField(null=True, upload_to='media/cloth/%Y/%m/%d/'),
        ),
    ]
