# Generated by Django 3.1.7 on 2022-02-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderssummary_clothimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderssummary',
            old_name='clothimage',
            new_name='cloth_image',
        ),
    ]
