# Generated by Django 3.1.7 on 2022-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20220215_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderssummary',
            name='quntity',
            field=models.IntegerField(null=True),
        ),
    ]
