# Generated by Django 3.1.7 on 2022-02-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderssummary_quntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderssummary',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
