# Generated by Django 3.1.7 on 2022-02-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220215_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderssummary',
            name='cloth_image',
            field=models.ImageField(null=True, upload_to='media/clent_profile_pic/%Y/%m/%d/'),
        ),
    ]
