# Generated by Django 3.1.7 on 2022-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20220215_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderssummary',
            name='cloth_image',
            field=models.ImageField(null=True, upload_to='media/service/%Y/%m/%d/'),
        ),
    ]
