# Generated by Django 3.1.7 on 2022-02-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20220217_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderssummary',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
