# Generated by Django 3.1.7 on 2022-02-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20220217_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderssummary',
            old_name='delivery_date',
            new_name='delivery',
        ),
    ]
