# Generated by Django 3.1.7 on 2022-02-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20220217_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderssummary',
            name='delivery',
            field=models.DateField(null=True),
        ),
    ]
