# Generated by Django 3.1.7 on 2022-02-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_paymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cloth_name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=150)),
                ('ironing', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('cold_water', models.BooleanField(default=False)),
                ('washing_liquid', models.BooleanField(default=False)),
                ('softern', models.BooleanField(default=False)),
                ('pick_up_date', models.DateField()),
                ('delivery', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
