# Generated by Django 3.1.7 on 2022-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20220217_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='image',
            field=models.ImageField(null=True, upload_to='media/payment/'),
        ),
    ]
