# Generated by Django 3.1.7 on 2022-02-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_paymentdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='media/coth/category/'),
        ),
    ]
