# Generated by Django 3.2.3 on 2022-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20220226_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderssummary',
            name='delivery_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderssummary',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
    ]
