# Generated by Django 3.2.3 on 2022-04-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20220404_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderssummary',
            name='cloth_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='orderssummary',
            name='instruction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
